### ISSUE TITLE
not full range of utf8.

### ISSUE THREAD

**Issue by agugu2000** [deividAlfa/UGUI#1]
Because of the logic of locating the font data,the utf8 support ends with 0x8000

**Comment by agugu2000** [comment]
OK,I think I work this out
Thank you for your original code.

https://github.com/agugu2000/UGUI
https://github.com/agugu2000/ttf2ugui

**Comment by deividAlfa** [comment]
Hey, I've been away for a while. I've just updated uGUI and ttf2ugui adding full unicode support.
These changes make it incompatible with old fonts!

**Comment by agugu2000** [comment]
> Hey, I've been away for a while. I've just updated uGUI and ttf2ugui adding full unicode support. These changes make it incompatible with old fonts! Instead making your own fork, please consider opening a pull request, so we get all the fixes in one place. Cheers!

My fork was just for me to practice C at the beginning. It has conflicts with the main branch now, and it’s been a long time since I worked on it. I’ve kind of forgotten about it, hahahaha. Just leave it alone and never mind. No one will care about my fork. Thanks for your current update, dude.
